server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    #    waitTimeInMsWhenSyncEmpty: 0
    #    renewalPercentThreshold: 0.49
    enableSelfPreservation: false
